#!/bin/bash

# This file was created to automate and optimize the monitor mode
# activation process while automatically detecting the wireless interface.

# Detect the first available wireless interface.
WIFI_IFACE=$(iw dev | awk '$1=="Interface"{print $2; exit}')

# Verify that a wireless interface was found before proceeding.
if [ -z "$WIFI_IFACE" ]; then
    echo "No wireless interface detected."
    exit 1
fi

# We run airmon-ng check kill to identify and terminate background services
# (such as NetworkManager, wpa_supplicant, or dhclient) that may interfere
# with enabling monitor mode on the wireless interface.
sudo airmon-ng check kill

# We start monitor mode on the detected wireless interface.
sudo airmon-ng start "$WIFI_IFACE"

# We define the monitor mode interface name generated by airmon-ng.
MON_IFACE="${WIFI_IFACE}mon"

# Verify that the monitor interface exists.
if ! ip link show "$MON_IFACE" >/dev/null 2>&1; then
    echo "Monitor interface not found: $MON_IFACE"
    exit 1
fi

# We temporarily disable the monitor interface to allow modifications
# to be applied safely.
sudo ip link set "$MON_IFACE" down

# We assign a random MAC address to the monitor interface to increase
# privacy and reduce hardware traceability during wireless monitoring.
sudo macchanger -r "$MON_IFACE"

# We bring the monitor interface back online so it is ready for use
# in monitor mode operations.
sudo ip link set "$MON_IFACE" up

# Display the active monitor interface.
echo "Monitor mode enabled on: $MON_IFACE"
